# Generated by Django 5.2.7 on 2025-10-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotion',
            new_name='promotions',
        ),
    ]
