# Generated by Django 5.2.7 on 2025-10-26 21:44

import apps.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[apps.store.validators.validate_file_size]),
        ),
    ]
